<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Seu Título Aqui</title>
  <style>
    body {
      margin: 0;
      padding: 0;
    }

    header {
          background-color: #001366; /* Cor ciano escuro */
      color: #fff; /* Cor do texto (branco) */
      text-align: center; /* Texto centralizado */
      padding: 20px; /* Espaçamento interno */
    }
  </style>
</head>
<body>

  <header>
    <h1>Meu Portifólio</h1>
  </header>

  <!-- Restante do conteúdo aqui -->

</body>
</html>
